global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-metrics-scrap'
    static_configs:
      - targets: ['node-app:3001']
  # - job_name: 'prometheus-metrics-scrap'
  #   static_config:
  #     - targets: ['prometheus:9090']
